//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSite.Common {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Common.ICommon")]
    public interface ICommon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/AddUser", ReplyAction="http://tempuri.org/ICommon/AddUserResponse")]
        CommonLibrary.Entities.User AddUser(CommonLibrary.Entities.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/RemoveUser", ReplyAction="http://tempuri.org/ICommon/RemoveUserResponse")]
        bool RemoveUser(CommonLibrary.Entities.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetUser", ReplyAction="http://tempuri.org/ICommon/GetUserResponse")]
        CommonLibrary.Entities.User GetUser(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetUsers", ReplyAction="http://tempuri.org/ICommon/GetUsersResponse")]
        CommonLibrary.Entities.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetAllItems", ReplyAction="http://tempuri.org/ICommon/GetAllItemsResponse")]
        CommonLibrary.Entities.Item[] GetAllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/AddItem", ReplyAction="http://tempuri.org/ICommon/AddItemResponse")]
        CommonLibrary.Entities.Item AddItem(CommonLibrary.Entities.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/Remove", ReplyAction="http://tempuri.org/ICommon/RemoveResponse")]
        bool Remove(CommonLibrary.Entities.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetItem", ReplyAction="http://tempuri.org/ICommon/GetItemResponse")]
        CommonLibrary.Entities.Item GetItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetShoppingCard", ReplyAction="http://tempuri.org/ICommon/GetShoppingCardResponse")]
        CommonLibrary.Entities.Item[] GetShoppingCard(CommonLibrary.Entities.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetOrder", ReplyAction="http://tempuri.org/ICommon/GetOrderResponse")]
        CommonLibrary.Entities.Item[] GetOrder(CommonLibrary.Entities.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/MakeOrder", ReplyAction="http://tempuri.org/ICommon/MakeOrderResponse")]
        bool MakeOrder(CommonLibrary.Entities.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/AddToCardItem", ReplyAction="http://tempuri.org/ICommon/AddToCardItemResponse")]
        CommonLibrary.Entities.Item[] AddToCardItem(CommonLibrary.Entities.User user, CommonLibrary.Entities.Item item, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/RemoveFromCard", ReplyAction="http://tempuri.org/ICommon/RemoveFromCardResponse")]
        bool RemoveFromCard(CommonLibrary.Entities.User user, CommonLibrary.Entities.Item item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetBuyHistory", ReplyAction="http://tempuri.org/ICommon/GetBuyHistoryResponse")]
        CommonLibrary.Entities.BuyHistoryItem[] GetBuyHistory();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonChannel : MainSite.Common.ICommon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonClient : System.ServiceModel.ClientBase<MainSite.Common.ICommon>, MainSite.Common.ICommon {
        
        public CommonClient() {
        }
        
        public CommonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommonLibrary.Entities.User AddUser(CommonLibrary.Entities.User user) {
            return base.Channel.AddUser(user);
        }
        
        public bool RemoveUser(CommonLibrary.Entities.User user) {
            return base.Channel.RemoveUser(user);
        }
        
        public CommonLibrary.Entities.User GetUser(string login) {
            return base.Channel.GetUser(login);
        }
        
        public CommonLibrary.Entities.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public CommonLibrary.Entities.Item[] GetAllItems() {
            return base.Channel.GetAllItems();
        }
        
        public CommonLibrary.Entities.Item AddItem(CommonLibrary.Entities.Item item) {
            return base.Channel.AddItem(item);
        }
        
        public bool Remove(CommonLibrary.Entities.Item item) {
            return base.Channel.Remove(item);
        }
        
        public CommonLibrary.Entities.Item GetItem(int id) {
            return base.Channel.GetItem(id);
        }
        
        public CommonLibrary.Entities.Item[] GetShoppingCard(CommonLibrary.Entities.User user) {
            return base.Channel.GetShoppingCard(user);
        }
        
        public CommonLibrary.Entities.Item[] GetOrder(CommonLibrary.Entities.User user) {
            return base.Channel.GetOrder(user);
        }
        
        public bool MakeOrder(CommonLibrary.Entities.User user) {
            return base.Channel.MakeOrder(user);
        }
        
        public CommonLibrary.Entities.Item[] AddToCardItem(CommonLibrary.Entities.User user, CommonLibrary.Entities.Item item, int count) {
            return base.Channel.AddToCardItem(user, item, count);
        }
        
        public bool RemoveFromCard(CommonLibrary.Entities.User user, CommonLibrary.Entities.Item item) {
            return base.Channel.RemoveFromCard(user, item);
        }
        
        public CommonLibrary.Entities.BuyHistoryItem[] GetBuyHistory() {
            return base.Channel.GetBuyHistory();
        }
    }
}
